apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: notes-pipeline
description: Notes app delivery pipeline
serialPipeline:
  stages:
  - targetId: dev
    profiles:
    - dev
  - targetId: staging
    profiles:
    - staging
  - targetId: prod
    profiles:
    - prod
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: dev target
run:
  location: projects/trainocat-1773203046724/locations/us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: staging target
run:
  location: projects/trainocat-1773203046724/locations/us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: prod target
run:
  location: projects/trainocat-1773203046724/locations/us-central1
