steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/notes-repo/notes-app:${_COMMIT_SHA}'
      - '.'

  # Push the container image to Artifact Registry 1
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/notes-repo/notes-app:${_COMMIT_SHA}'


images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/notes-repo/notes-app:${_COMMIT_SHA}'
options:
     logging: CLOUD_LOGGING_ONLY
substitutions:
     _COMMIT_SHA: $(_SHORT_SHA)
